title: This blog is awesome
author: Giulio Foletto
email: not.your@business.com
description: > # this means to ignore newlines until "baseurl:"
  This blog was created for the github learning lab course

# social links
github_username:  giuliofoletto # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
